name: Fastlane checks

on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
      - 'hotfix/*'
      
jobs:
  check_description_length:
    name: Check Fastlane description is at most 500 chars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print all file sizes for debugging
        run: wc -m fastlane/metadata/android/*/full_description.txt
      - name: Check all files have at most 500 characters
        run: |
          for s in fastlane/metadata/android/*/full_description.txt; do
          size=($(wc -m "$s"));
          if [ ${size[0]} -gt 500 ]; 
          then 
          echo "File ${size[1]} is longer than 500 characters (is ${size[0]})";
          exit 1; 
          fi
          done
         
       
